"""Built-in MDP terms, grouped by manager (actions, rewards, observations, ...)."""

from eden.managers.terms.actions import (
    ImplicitPDController,
    ExplicitPDController,
    DifferentialIKController,
)
from eden.managers.terms.commands import (
    UniformSE3Command,
    UniformT3Command,
)
from eden.managers.terms.events import (
    RandomizeDofsPosOffset,
    PushByVelocity,
    RandomizeFrictionRatio,
    RandomizeMassShift,
    RandomizeComShift,
    place_constant_xy,
    place_range_xy,
    place_uniform,
    PlaceGaussian,
)
from eden.managers.terms.metrics import (
    object_a_is_on_b,
    error_vel_xy,
    error_vel_yaw,
    entity_distance,
    entity_distance_xy,
    entity_near_target,
    entity_near_entity_xy,
    EeNearEntity,
    object_above_height,
    object_in_region,
    object_lifted,
    IsGrasping,
    joint_angle_at_target,
    SequentialMetricTerm,
    PhaseOptions,
    MetricTermAND,
    MetricTermOR,
    MetricTermNOT,
)
from eden.managers.terms.observations import (
    generated_commands,
    last_action,
    base_pos,
    base_quat,
    base_rpy,
    base_lin_vel,
    base_ang_vel,
    dofs_pos,
    dofs_vel,
    dofs_force,
    dofs_control_force,
    links_pos,
    links_quat,
    links_vel,
    links_ang,
)
from eden.managers.terms.rewards import (
    action_rate_l2,
    action_l2,
    dofs_pos_limits,
    self_collision_cost,
    similar_to_default,
)
from eden.managers.terms.recorders import (
    ActionRecorder,
    SensorRecorder,
    StateRecorder,
    InitialStateRecorder,
)
from eden.managers.terms.terminations import (
    time_out,
)


__all__ = [
    "ImplicitPDController",
    "ExplicitPDController",
    "DifferentialIKController",
    "UniformSE3Command",
    "UniformT3Command",
    "RandomizeDofsPosOffset",
    "PushByVelocity",
    "RandomizeFrictionRatio",
    "RandomizeMassShift",
    "RandomizeComShift",
    "place_constant_xy",
    "place_range_xy",
    "place_uniform",
    "PlaceGaussian",
    "generated_commands",
    "last_action",
    "base_pos",
    "base_quat",
    "base_rpy",
    "base_lin_vel",
    "base_ang_vel",
    "dofs_pos",
    "dofs_vel",
    "dofs_force",
    "dofs_control_force",
    "links_pos",
    "links_quat",
    "links_vel",
    "links_ang",
    "action_rate_l2",
    "action_l2",
    "dofs_pos_limits",
    "self_collision_cost",
    "similar_to_default",
    "time_out",
    "ActionRecorder",
    "SensorRecorder",
    "StateRecorder",
    "InitialStateRecorder",
    "object_a_is_on_b",
    "error_vel_xy",
    "error_vel_yaw",
    "entity_distance",
    "entity_distance_xy",
    "entity_near_target",
    "entity_near_entity_xy",
    "EeNearEntity",
    "object_above_height",
    "object_in_region",
    "object_lifted",
    "IsGrasping",
    "joint_angle_at_target",
    "SequentialMetricTerm",
    "PhaseOptions",
    "MetricTermAND",
    "MetricTermOR",
    "MetricTermNOT",
]
